Feature: Interactions Website
	Checks the features of the interactions page of the website

Scenario: Login Success ---> Add Interaction (Minimal) 
	Given I am on "http://54.201.147.95/console/login"
	When I fill in "_username" with "admin@antic.com"
	When I fill in "_password" with "admin"
	And I press "submit"
	And I follow "interactionsList"
	Then the url should match "/console/interactions"
	When I follow "addInteraction"
	Then the url should match "/console/interactions/add"
	When I fill in "name" with "Behat CYP 1"
	When I press "saveInteraction"
	Then the url should match "/console/interactions"
	Then I should not see "Behat CYP 1"
	
Scenario: Login Success ---> Add Interaction (Normal)
	Given I am on "http://54.201.147.95/console/login"
	When I fill in "_username" with "admin@antic.com"
	When I fill in "_password" with "admin"
	And I press "submit"
	And I follow "interactionsList"
	Then the url should match "/console/interactions"
	When I follow "addInteraction"
	Then the url should match "/console/interactions/add"
	When I fill in "name" with "Behat CYP 2"
	When I fill in "substrate[0][name]" with "Int-1"
	When I fill in "substrate[0][risk]" with "Unknown"
	When I fill in "inducer[0][name]" with "Int-2"
	When I fill in "inducer[0][risk]" with "Strong"
	When I fill in "inhibitor[0][name]" with "Int-3"
	When I fill in "inhibitor[0][risk]" with "Moderate"
	Then the url should match "/console/interactions"
	When I press "saveInteraction"
	Then the url should match "/console/interactions"
	Then I should ee "Behat CYP 2"
	
Scenario: Login Success ---> Add Interaction (Bulky)
	Given I am on "http://54.201.147.95/console/login"
	When I fill in "_username" with "admin@antic.com"
	When I fill in "_password" with "admin"
	And I press "submit"
	And I follow "interactionsList"
	Then the url should match "/console/interactions"
	When I follow "addInteraction"
	Then the url should match "/console/interactions/add"
	When I fill in "name" with "Behat CYP 3"
	And I press "addMoreSubstrate"
	And I press "addMoreSubstrate"
	And I press "addMoreSubstrate"
	And I press "addMoreSubstrate"
	And I press "addMoreInducer"
	And I press "addMoreInducer"
	And I press "addMoreInducer"
	And I press "addMoreInducer"
	And I press "addMoreInhibitor"
	And I press "addMoreInhibitor"
	And I press "addMoreInhibitor"
	And I press "addMoreInhibitor"
	When I fill in "substrate[0][name]" with "Int-1"
	When I fill in "substrate[0][risk]" with "Unknown"
	When I fill in "inducer[0][name]" with "Int-2"
	When I fill in "inducer[0][risk]" with "Strong"
	When I fill in "inhibitor[0][name]" with "Int-3"
	When I fill in "inhibitor[0][risk]" with "Moderate"
	When I fill in "substrate[1][name]" with "Int-4"
	When I fill in "substrate[1][risk]" with "Weak"
	When I fill in "inducer[1][name]" with "Int-5"
	When I fill in "inducer[1][risk]" with "Unknown"
	When I fill in "inhibitor[1][name]" with "Int-6"
	When I fill in "inhibitor[1][risk]" with "Strong"
	When I fill in "substrate[2][name]" with "Int-8"
	When I fill in "substrate[2][risk]" with "Moderate"
	When I fill in "inducer[2][name]" with "Int-9"
	When I fill in "inducer[2][risk]" with "Weak"
	When I fill in "inhibitor[2][name]" with "Int-10"
	When I fill in "inhibitor[2][risk]" with "Unknown"
	When I fill in "substrate[3][name]" with "Int-11"
	When I fill in "substrate[3][risk]" with "Strong"
	When I fill in "inducer[3][name]" with "Int-12"
	When I fill in "inducer[3][risk]" with "Moderate"
	When I fill in "inhibitor[3][name]" with "Int-13"
	When I fill in "inhibitor[3][risk]" with "Weak"
	When I fill in "substrate[4][name]" with "Int-14"
	When I fill in "substrate[4][risk]" with "Unknown"
	When I fill in "inducer[4][name]" with "Int-15"
	When I fill in "inducer[4][risk]" with "Weak"
	When I fill in "inhibitor[4][name]" with "Int-16"
	When I fill in "inhibitor[4][risk]" with "Strong"
	Then the url should match "/console/interactions"
	When I press "saveInteraction"
	Then the url should match "/console/interactions"
	Then I should see "Behat CYP 3"